title: Meow, meow
author: Felipe Nogueira
email: contato.fnog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I loved dogs until I discovered cats.

theme: minima
# social links
github_username:  fnogcps # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
